name: Migration Test

on: [pull_request]
        
jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:

    - name: spin up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: hca_dev
        postgresql user: hca_dev
        postgresql password: hca_dev

    - name: checkout branch
      uses: actions/checkout@v2
    
    - name: download flyway
      run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.3.1/flyway-commandline-6.3.1-linux-x64.tar.gz | tar xvz
    
    # run migrate for each database
    - name: migrate datamart db
      run: ./flyway-6.3.1/flyway migrate -configFiles=./data-mart/databases/datamart/dev.conf 